# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtunesapp', '0003_auto_20170421_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='set_to_expire',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
