# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtunesapp', '0005_auto_20170421_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audio_file',
            field=models.CharField(default='sadface.mp3', max_length=100),
        ),
    ]
